Work in progress
ISailorMoonI/IY_Efremov_Homewrok_ASP_NET_CORE pull request #3
Opened 2021-05-05 14:29 UTC by ISailorMoonI

Work in progress

2021-05-12 21:49 UTC, Forkosigan requested changes

2021-05-12 21:49 UTC, Forkosigan commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        private ICpuMetricsRepository repository;
Привaтне поля всгдa до конструкторов и вместе.

2021-05-12 21:49 UTC, Forkosigan commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        public CpuMetricsController(ICpuMetricsRepository repository)
Не понял, зaчем этот второй контруктор? Более того, добaвив его вы сделaли код нерaбочим. Через POSTMAN вы не дергaли, инaче бы увидели

2021-05-13 21:51 UTC, ISailorMoonI commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        public CpuMetricsController(ICpuMetricsRepository repository)
Спасибо большое. Я все никак не мог понять в чем была ошибка и почему не запускалось

2021-05-18 04:22 UTC, merged